Fix build with OpenSSL 1.1 due to EVP_PKEY being an opaque struct
With OpenSSL 1.1 the build fails with:
data_import.c:375:26: error: dereferencing pointer to incomplete type
'EVP_PKEY {aka struct evp_pkey_st}'

The manual page[1] says:
  Previous versions of this document suggested using
  EVP_PKEY_type(pkey->type) to determine the type of a key. Since EVP_PKEY
  is now opaque this is no longer possible: the equivalent is
  EVP_PKEY_base_id(pkey).

[1] https://www.openssl.org/docs/man1.1.0/crypto/EVP_PKEY_base_id.html

Signed-off-by: Debora Velarde Babb <debora@linux.ibm.com>